let unified wrapper to update the potential between calculations
libAtoms/QUIP pull request #242
Opened 2020-10-06 20:53 UTC by stenczelt

Unified wrapper is enabled to update the potential from one to another calculation while in the same run.
Same for the castep wrapper

2020-10-06 21:23 UTC, albapa requested changes
1. Do not use the `write` statement, use `call print()` instead.
2. Why `else  if`? Why not another `if`?

2020-10-07 07:33 UTC, stenczelt commented
1. ok, on it
2. if it is the first pass, then there is no point re-reading it if the previous if clause initialised it

2020-10-07 08:49 UTC, albapa requested changes
What I think needs to be done differently is that `lattice` and `reload_pot` are coupled in the `if` `else if` construct. I think they should be decoupled. Also, `reload_pot` is an optional argument and shouldn't be checked like that in the `if`. Please look at the `optional_default()` function we use in such situations.

2020-10-07 10:58 UTC, stenczelt commented
What happens if the atom types are changing? ie. I initialise with [Si, Si, O] and pass a cell with [Si, O, O]?

2020-10-09 15:16 UTC, albapa approved these changes

2020-10-09 15:16 UTC, merged